FROM python:3.11-slim-bullseye as compile-image
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
COPY --from=infra requirements.dev .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.dev

FROM python:3.11-slim-bullseye
COPY --from=compile-image /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /app
COPY . /app/bot
CMD ["python", "-m", "bot"]
